#server:
#  port: XXXX ## This property will be read but have no effect.

spring:
  profiles:
    active: git # This property must be present otherwise the only the default config will be served.
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Work/kelin/SpringCloud/spring-cloud-app-config-repo
