server:
  port: ${CONFIGSERVER_PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kevinlinxp/spring-cloud-app-config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://cloudapp-eureka-server:${EUREKASERVER_PORT:8761}/eureka