server:
  port: ${CONFIGSERVER_PORT:8888}

spring:
#  profiles:
#    active: git
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Work/kelin/SpringCloud/spring-cloud-app-config-repo
